package com.ammar.wallflow.utils

object NotificationIds {
    const val AUTO_WALLPAPER_NOTIFICATION_ID = 100
    const val AUTO_WALLPAPER_SUCCESS_NOTIFICATION_ID = 101
    const val AUTO_WALLPAPER_HOME_SUCCESS_NOTIFICATION_ID = 102
    const val AUTO_WALLPAPER_LOCK_SUCCESS_NOTIFICATION_ID = 103
    const val CLEANUP_NOTIFICATION_ID = 900
}
